#include "gestionnavires.h"
#include "navire_stats_dialog.h"
#include "navire_history_dialog.h"
#include "navire_interdit_dialog.h"
#include "navire_chatbot_dialog.h"
#include "../AppTheme.h"

#include <QSqlQuery>
#include <QSqlQueryModel>
#include <QSqlError>
#include <QSqlDatabase>
#include <QMessageBox>
#include <QDebug>
#include <QRegularExpression>
#include <QPdfWriter>
#include <QPainter>
#include <QFileDialog>
#include <QHeaderView>
#include <QGroupBox>
#include <QFormLayout>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QLabel>
#include <QLineEdit>
#include <QSpinBox>
#include <QComboBox>
#include <QPushButton>
#include <QTableView>
#include <QFrame>
#include <QStyle>
#include <QPageSize>
#include <QPageLayout>

// ── helper: section title label ──────────────────────────────────────────────
static QLabel *sectionTitle(const QString &text) {
    auto *l = new QLabel(text);
    l->setStyleSheet("font-size:14px;font-weight:800;color:#0a1628;margin-bottom:4px;");
    return l;
}

// ── helper: make action button ───────────────────────────────────────────────
static QPushButton *mkBtn(const QString &text, const QString &style) {
    auto *b = new QPushButton(text);
    b->setStyleSheet(style);
    b->setCursor(Qt::PointingHandCursor);
    return b;
}

GestionNavires::GestionNavires(QWidget *parent)
    : QWidget(parent)
    , m_model(nullptr)
    , m_currentSort("id_navire ASC")
    , m_trayIcon(new QSystemTrayIcon(this))
{
    setStyleSheet(AppTheme::widgetStyle());

    auto *root = new QHBoxLayout(this);
    root->setContentsMargins(16,16,16,16);
    root->setSpacing(16);

    // ══════════════════════════════════════════════════════════════════════════
    // LEFT PANEL — form
    // ══════════════════════════════════════════════════════════════════════════
    auto *leftPanel = new QFrame;
    leftPanel->setFixedWidth(300);
    leftPanel->setStyleSheet("QFrame{background:#ffffff;border-radius:12px;"
                             "border:1px solid #e2e8f0;}");
    auto *leftBox = new QVBoxLayout(leftPanel);
    leftBox->setContentsMargins(16,16,16,16);
    leftBox->setSpacing(10);

    leftBox->addWidget(sectionTitle("⚓  Informations du navire"));

    auto *formLayout = new QFormLayout;
    formLayout->setSpacing(8);
    formLayout->setLabelAlignment(Qt::AlignRight);

    spinBox_id_navire = new QSpinBox; spinBox_id_navire->setMinimum(1);
    lineEdit_nom = new QLineEdit;     lineEdit_nom->setPlaceholderText("Ex: Neptune");
    lineEdit_immatriculation = new QLineEdit; lineEdit_immatriculation->setPlaceholderText("Chiffres uniquement");
    lineEdit_type = new QLineEdit;    lineEdit_type->setPlaceholderText("Ex: Cargo");
    spinBox_capacite = new QSpinBox;  spinBox_capacite->setMinimum(1); spinBox_capacite->setMaximum(99999);
    spinBox_capacite->setSuffix(" t");
    comboBox_statut = new QComboBox;
    comboBox_statut->addItems({"à quai", "en mer", "interdit"});

    spinBox_id_navire->hide(); // auto-generated by Oracle IDENTITY
    formLayout->addRow("Nom :",            lineEdit_nom);
    formLayout->addRow("Immatriculation :",lineEdit_immatriculation);
    formLayout->addRow("Type :",           lineEdit_type);
    formLayout->addRow("Capacité :",       spinBox_capacite);
    formLayout->addRow("Statut :",         comboBox_statut);
    leftBox->addLayout(formLayout);

    // CRUD buttons
    auto *crudRow1 = new QHBoxLayout;
    auto *btnAjouter   = mkBtn("➕ Ajouter",   AppTheme::btnSuccess());
    auto *btnModifier  = mkBtn("✏️ Modifier",  AppTheme::btnPrimary());
    crudRow1->addWidget(btnAjouter);
    crudRow1->addWidget(btnModifier);

    auto *crudRow2 = new QHBoxLayout;
    auto *btnSupprimer = mkBtn("🗑️ Supprimer", AppTheme::btnDanger());
    auto *btnVider     = mkBtn("🔄 Vider",     AppTheme::btnSlate());
    crudRow2->addWidget(btnSupprimer);
    crudRow2->addWidget(btnVider);

    leftBox->addLayout(crudRow1);
    leftBox->addLayout(crudRow2);
    leftBox->addStretch();

    // ══════════════════════════════════════════════════════════════════════════
    // RIGHT PANEL — search + table + footer
    // ══════════════════════════════════════════════════════════════════════════
    auto *rightPanel = new QFrame;
    rightPanel->setStyleSheet("QFrame{background:#ffffff;border-radius:12px;"
                              "border:1px solid #e2e8f0;}");
    auto *rightBox = new QVBoxLayout(rightPanel);
    rightBox->setContentsMargins(16,16,16,16);
    rightBox->setSpacing(10);

    rightBox->addWidget(sectionTitle("🚢  Liste des navires"));

    // Search + filter + sort bar
    auto *searchBar = new QHBoxLayout;
    lineEdit_recherche = new QLineEdit;
    lineEdit_recherche->setPlaceholderText("🔍  Rechercher par nom...");
    comboBox_filtre_statut = new QComboBox;
    comboBox_filtre_statut->addItems({"Tous les statuts","à quai","en mer","interdit"});
    auto *btnTriAsc  = mkBtn("↑ Asc",  AppTheme::btnSlate());
    auto *btnTriDesc = mkBtn("↓ Desc", AppTheme::btnSlate());
    btnTriAsc->setFixedWidth(70);
    btnTriDesc->setFixedWidth(70);
    searchBar->addWidget(lineEdit_recherche, 1);
    searchBar->addWidget(comboBox_filtre_statut);
    searchBar->addWidget(btnTriAsc);
    searchBar->addWidget(btnTriDesc);
    rightBox->addLayout(searchBar);

    // Table
    tableView_navires = new QTableView;
    tableView_navires->setSelectionBehavior(QAbstractItemView::SelectRows);
    tableView_navires->setSelectionMode(QAbstractItemView::SingleSelection);
    tableView_navires->setEditTriggers(QAbstractItemView::NoEditTriggers);
    tableView_navires->setAlternatingRowColors(true);
    tableView_navires->setStyleSheet(
        "QTableView{alternate-background-color:#f8fafc;}"
        "QTableView::item{padding:6px;border-bottom:1px solid #f1f5f9;}"
        "QTableView::item:selected{background:#dbeafe;color:#1e3a8a;}"
    );
    rightBox->addWidget(tableView_navires, 1);

    // Footer buttons
    auto *footer = new QHBoxLayout;
    auto *btnPdf  = mkBtn("📄 Export PDF",    AppTheme::btnSlate());
    auto *btnStat = mkBtn("📊 Statistiques",  AppTheme::btnPrimary());
    auto *btnHist = mkBtn("🕓 Historique",    AppTheme::btnSlate());
    auto *btnBot  = mkBtn("🤖 Chatbot IA",    AppTheme::btnPurple());
    footer->addWidget(btnPdf);
    footer->addWidget(btnStat);
    footer->addWidget(btnHist);
    footer->addStretch();
    footer->addWidget(btnBot);
    rightBox->addLayout(footer);

    root->addWidget(leftPanel);
    root->addWidget(rightPanel, 1);

    // ── Connections ───────────────────────────────────────────────────────────
    connect(btnAjouter,   &QPushButton::clicked, this, &GestionNavires::on_pushButton_ajouter_clicked);
    connect(btnModifier,  &QPushButton::clicked, this, &GestionNavires::on_pushButton_modifier_clicked);
    connect(btnSupprimer, &QPushButton::clicked, this, &GestionNavires::on_pushButton_supprimer_clicked);
    connect(btnVider,     &QPushButton::clicked, this, &GestionNavires::viderFormulaire);
    connect(btnTriAsc,    &QPushButton::clicked, this, &GestionNavires::on_pushButton_tri_asc_clicked);
    connect(btnTriDesc,   &QPushButton::clicked, this, &GestionNavires::on_pushButton_tri_desc_clicked);
    connect(btnPdf,       &QPushButton::clicked, this, &GestionNavires::on_pushButton_export_pdf_clicked);
    connect(btnStat,      &QPushButton::clicked, this, &GestionNavires::on_pushButton_stats_clicked);
    connect(btnHist,      &QPushButton::clicked, this, &GestionNavires::on_pushButton_historique_clicked);
    connect(btnBot,       &QPushButton::clicked, this, &GestionNavires::on_pushButton_chatbot_clicked);
    connect(tableView_navires, &QTableView::clicked, this, &GestionNavires::on_tableView_navires_clicked);
    connect(lineEdit_recherche, &QLineEdit::textChanged, this, &GestionNavires::on_lineEdit_recherche_textChanged);
    connect(comboBox_filtre_statut, QOverload<int>::of(&QComboBox::currentIndexChanged),
            this, &GestionNavires::on_comboBox_filtre_statut_currentIndexChanged);
    connect(lineEdit_nom,             &QLineEdit::textChanged, this, [this](){ controlerSaisie(); });
    connect(lineEdit_immatriculation, &QLineEdit::textChanged, this, [this](){ controlerSaisie(); });
    connect(lineEdit_type,            &QLineEdit::textChanged, this, [this](){ controlerSaisie(); });
    connect(spinBox_id_navire,  QOverload<int>::of(&QSpinBox::valueChanged), this, [this](){ controlerSaisie(); });
    connect(spinBox_capacite,   QOverload<int>::of(&QSpinBox::valueChanged), this, [this](){ controlerSaisie(); });

    m_trayIcon->setIcon(style()->standardIcon(QStyle::SP_MessageBoxWarning));
    m_trayIcon->show();
}

// ── loadFromDb ────────────────────────────────────────────────────────────────
void GestionNavires::loadFromDb()
{
    auto db = QSqlDatabase::database();
    QSqlQuery qArc(db);
    qArc.exec("CREATE TABLE navire ("
              "id_navire NUMBER PRIMARY KEY, "
              "nom VARCHAR2(100), "
              "immatriculation VARCHAR2(100), "
              "type VARCHAR2(100), "
              "capacite NUMBER, "
              "statut VARCHAR2(100))");

    initialiserTable();

    QSqlQuery qInt(db);
    qInt.exec("SELECT COUNT(*) FROM navire WHERE statut = 'interdit'");
    int count = 0;
    if (qInt.next()) count = qInt.value(0).toInt();
    m_trayIcon->showMessage("Flotte de Navires",
                            QString("Il y a %1 navire(s) interdit(s) dans la flotte.").arg(count),
                            QSystemTrayIcon::Information, 3000);
    if (count > 0) {
        NavireInterditDialog diag(db, this);
        diag.exec();
        rafraichirTable();
    }
    controlerSaisie();
}

// ── initialiserTable ──────────────────────────────────────────────────────────
void GestionNavires::initialiserTable()
{
    auto db = QSqlDatabase::database();
    if (!db.isOpen()) return;
    delete m_model;
    m_model = new QSqlQueryModel(this);
    tableView_navires->setModel(m_model);
    tableView_navires->horizontalHeader()->setSectionResizeMode(QHeaderView::Stretch);
    tableView_navires->verticalHeader()->setVisible(false);
    rafraichirTable();
}

// ── rafraichirTable ───────────────────────────────────────────────────────────
void GestionNavires::rafraichirTable(const QString &filtreNom,
                                      const QString &filtreStatut,
                                      const QString &triOrder)
{
    auto db = QSqlDatabase::database();
    if (!m_model || !db.isOpen()) return;
    m_currentSort = triOrder;

    QString sql = "SELECT id_navire, nom, immatriculation, type, capacite, statut FROM navire";
    QStringList filters;
    if (!filtreNom.isEmpty())
        filters << "LOWER(nom) LIKE LOWER('%" + filtreNom + "%')";
    if (filtreStatut != "Tous les statuts")
        filters << "statut = '" + filtreStatut + "'";
    if (!filters.isEmpty()) sql += " WHERE " + filters.join(" AND ");
    sql += " ORDER BY " + m_currentSort;

    m_model->setQuery(sql, db);
    if (m_model->lastError().isValid())
        qDebug() << "SQL Error:" << m_model->lastError().text();

    m_model->setHeaderData(0, Qt::Horizontal, "ID");
    m_model->setHeaderData(1, Qt::Horizontal, "Nom");
    m_model->setHeaderData(2, Qt::Horizontal, "Immatriculation");
    m_model->setHeaderData(3, Qt::Horizontal, "Type");
    m_model->setHeaderData(4, Qt::Horizontal, "Capacité");
    m_model->setHeaderData(5, Qt::Horizontal, "Statut");
}

// ── viderFormulaire ───────────────────────────────────────────────────────────
void GestionNavires::viderFormulaire()
{
    spinBox_id_navire->setValue(1);
    lineEdit_nom->clear();
    lineEdit_immatriculation->clear();
    lineEdit_type->clear();
    spinBox_capacite->setValue(1);
    comboBox_statut->setCurrentIndex(0);
    controlerSaisie();
}

// ── idSelectionne ─────────────────────────────────────────────────────────────
int GestionNavires::idSelectionne() const
{
    QModelIndex index = tableView_navires->currentIndex();
    if (!index.isValid()) return -1;
    return m_model->data(m_model->index(index.row(), 0)).toInt();
}

// ── controlerSaisie ───────────────────────────────────────────────────────────
void GestionNavires::controlerSaisie()
{
    QString nom  = lineEdit_nom->text().trimmed();
    QString imm  = lineEdit_immatriculation->text().trimmed();
    QString type = lineEdit_type->text().trimmed();

    bool nomValide  = QRegularExpression("^[A-Za-zÀ-ÿ ]+$").match(nom).hasMatch()  && !nom.isEmpty();
    bool immValide  = QRegularExpression("^[0-9]+$").match(imm).hasMatch()           && !imm.isEmpty();
    bool typeValide = QRegularExpression("^[A-Za-zÀ-ÿ ]+$").match(type).hasMatch() && !type.isEmpty();

    auto upd = [](QLineEdit *le, bool valid, bool empty) {
        if (empty)       le->setStyleSheet("");
        else if (valid)  le->setStyleSheet("border:2px solid #059669;background:#f0fdf4;border-radius:6px;");
        else             le->setStyleSheet("border:2px solid #dc2626;background:#fef2f2;border-radius:6px;");
    };
    upd(lineEdit_nom,             nomValide,  nom.isEmpty());
    upd(lineEdit_immatriculation, immValide,  imm.isEmpty());
    upd(lineEdit_type,            typeValide, type.isEmpty());
}

// ── getStats ──────────────────────────────────────────────────────────────────
GestionNavires::NaviresStats GestionNavires::getStats() const
{
    NaviresStats s{0,0,0,0};
    if (!m_model) return s;
    s.total = m_model->rowCount();
    for (int i = 0; i < m_model->rowCount(); i++) {
        QString st = m_model->data(m_model->index(i, 5)).toString();
        if      (st == "à quai")   s.quai++;
        else if (st == "en mer")   s.mer++;
        else if (st == "interdit") s.interdit++;
    }
    return s;
}

// ── CRUD slots ────────────────────────────────────────────────────────────────
void GestionNavires::on_pushButton_ajouter_clicked()
{
    auto db = QSqlDatabase::database();
    if (!db.isOpen()) { QMessageBox::warning(this, "Base de données", "Connexion non ouverte."); return; }

    int id       = spinBox_id_navire->value();
    QString nom  = lineEdit_nom->text().trimmed();
    QString imm  = lineEdit_immatriculation->text().trimmed();
    QString type = lineEdit_type->text().trimmed();
    int cap      = spinBox_capacite->value();
    QString stat = comboBox_statut->currentText();

    if (nom.isEmpty() || imm.isEmpty() || type.isEmpty()) {
        QMessageBox::warning(this, "Champs manquants", "Veuillez remplir tous les champs obligatoires."); return;
    }
    QSqlQuery q(db);
    q.prepare("INSERT INTO navire (nom, immatriculation, type, capacite, statut) "
              "VALUES (:nom,:imm,:type,:cap,:stat)");
    q.bindValue(":nom",nom); q.bindValue(":imm",imm);
    q.bindValue(":type",type); q.bindValue(":cap",cap); q.bindValue(":stat",stat);
    if (!q.exec()) { QMessageBox::critical(this,"Erreur","Impossible d'ajouter : "+q.lastError().text()); return; }
    QMessageBox::information(this,"Succès","Navire ajouté avec succès.");
    rafraichirTable(); viderFormulaire();
}

void GestionNavires::on_pushButton_modifier_clicked()
{
    auto db = QSqlDatabase::database();
    if (!db.isOpen()) { QMessageBox::warning(this,"Base de données","Connexion non ouverte."); return; }
    int id = idSelectionne();
    if (id < 0) { QMessageBox::warning(this,"Sélection","Sélectionnez un navire à modifier."); return; }
    QSqlQuery q(db);
    q.prepare("UPDATE navire SET nom=:nom,immatriculation=:imm,type=:type,capacite=:cap,statut=:stat WHERE id_navire=:id");
    q.bindValue(":nom",lineEdit_nom->text()); q.bindValue(":imm",lineEdit_immatriculation->text());
    q.bindValue(":type",lineEdit_type->text()); q.bindValue(":cap",spinBox_capacite->value());
    q.bindValue(":stat",comboBox_statut->currentText()); q.bindValue(":id",id);
    if (!q.exec()) { QMessageBox::critical(this,"Erreur","Impossible de modifier : "+q.lastError().text()); return; }
    QMessageBox::information(this,"Succès","Navire modifié avec succès.");
    rafraichirTable();
}

void GestionNavires::on_pushButton_supprimer_clicked()
{
    auto db = QSqlDatabase::database();
    if (!db.isOpen()) { QMessageBox::warning(this,"Base de données","Connexion non ouverte."); return; }
    int id = idSelectionne();
    if (id < 0) { QMessageBox::warning(this,"Sélection","Sélectionnez un navire à supprimer."); return; }
    if (QMessageBox::question(this,"Confirmation","Voulez-vous vraiment supprimer ce navire ?") != QMessageBox::Yes) return;
    QSqlQuery qArc(db);
    qArc.prepare("INSERT INTO navire (id_navire,nom,immatriculation,type,capacite,statut) "
                 "SELECT id_navire,nom,immatriculation,type,capacite,statut FROM navire WHERE id_navire=:id");
    qArc.bindValue(":id",id); qArc.exec();
    QSqlQuery q(db);
    q.prepare("DELETE FROM navire WHERE id_navire=:id");
    q.bindValue(":id",id);
    if (!q.exec()) { QMessageBox::critical(this,"Erreur","Impossible de supprimer : "+q.lastError().text()); return; }
    rafraichirTable(); viderFormulaire();
}

void GestionNavires::on_tableView_navires_clicked(const QModelIndex &index)
{
    if (!index.isValid()) return;
    int row = index.row();
    spinBox_id_navire->setValue(m_model->data(m_model->index(row,0)).toInt());
    lineEdit_nom->setText(m_model->data(m_model->index(row,1)).toString());
    lineEdit_immatriculation->setText(m_model->data(m_model->index(row,2)).toString());
    lineEdit_type->setText(m_model->data(m_model->index(row,3)).toString());
    spinBox_capacite->setValue(m_model->data(m_model->index(row,4)).toInt());
    QString statut = m_model->data(m_model->index(row,5)).toString();
    int idx = comboBox_statut->findText(statut);
    if (idx >= 0) comboBox_statut->setCurrentIndex(idx);
    controlerSaisie();
}

void GestionNavires::on_lineEdit_recherche_textChanged(const QString &arg1)
{ rafraichirTable(arg1, comboBox_filtre_statut->currentText(), m_currentSort); }

void GestionNavires::on_comboBox_filtre_statut_currentIndexChanged(int)
{ rafraichirTable(lineEdit_recherche->text(), comboBox_filtre_statut->currentText(), m_currentSort); }

void GestionNavires::on_pushButton_tri_asc_clicked()
{ rafraichirTable(lineEdit_recherche->text(), comboBox_filtre_statut->currentText(), "immatriculation ASC"); }

void GestionNavires::on_pushButton_tri_desc_clicked()
{ rafraichirTable(lineEdit_recherche->text(), comboBox_filtre_statut->currentText(), "immatriculation DESC"); }

void GestionNavires::on_pushButton_export_pdf_clicked()
{
    QString fileName = QFileDialog::getSaveFileName(this,"Exporter en PDF","","Fichiers PDF (*.pdf)");
    if (fileName.isEmpty()) return;
    if (!fileName.endsWith(".pdf",Qt::CaseInsensitive)) fileName += ".pdf";
    QPdfWriter w(fileName);
    w.setPageSize(QPageSize(QPageSize::A4));
    w.setPageOrientation(QPageLayout::Landscape);
    w.setPageMargins(QMarginsF(30,30,30,30));
    QPainter p(&w);
    if (!p.isActive()) return;
    p.setFont(QFont("Arial",10));
    p.drawText(4000,500,"LISTE DES NAVIRES");
    int x=500,y=1500,xStep=1500,yStep=500;
    for (int j=0;j<m_model->columnCount();j++)
        p.drawText(x+j*xStep,y,m_model->headerData(j,Qt::Horizontal).toString());
    y+=yStep; p.drawLine(x,y-100,x+m_model->columnCount()*xStep,y-100);
    for (int i=0;i<m_model->rowCount();i++) {
        for (int j=0;j<m_model->columnCount();j++)
            p.drawText(x+j*xStep,y,m_model->data(m_model->index(i,j)).toString());
        y+=yStep; if(y>9000){w.newPage();y=1000;}
    }
    p.end();
    QMessageBox::information(this,"Export PDF","Liste exportée avec succès.");
}

void GestionNavires::on_pushButton_stats_clicked()
{ NavireStatsDialog d(QSqlDatabase::database(),this); d.exec(); rafraichirTable(); }

void GestionNavires::on_pushButton_historique_clicked()
{ NavireHistoryDialog d(QSqlDatabase::database(),this); d.exec(); rafraichirTable(); }

void GestionNavires::on_pushButton_chatbot_clicked()
{ NavireChatbotDialog d(QSqlDatabase::database(),this); d.exec(); }
